import { type Config } from "tailwindcss"

export default {
  // purge: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        blue: {
          50: "#dcdef9",
          100: "#d0d8ff",
          200: "#afcaff",
          300: "#8fc8ff",
          400: "#74cbff",
          500: "#5bcefa",
          600: "#41badc",
          700: "#2b99b2",
          800: "#1a6c7f",
          900: "#0c3a46",
        },
        lavender: {
          "50": "#faf5ff",
          "100": "#f2e8ff",
          "200": "#e8d5ff",
          "300": "#dfc5fe",
          "400": "#bc84fc",
          "500": "#a356f6",
          "600": "#8e34e9",
          "700": "#7923cd",
          "800": "#6722a7",
          "900": "#551c87",
          "950": "#380764",
        },
        eggplant: {
          "50": "#f9f6f8",
          "100": "#f5eef3",
          "200": "#eddde8",
          "300": "#dfc2d6",
          "400": "#ca9cbb",
          "500": "#b77da3",
          "600": "#a16187",
          "700": "#884e6f",
          "800": "#72425c",
          "900": "#5c384c",
          "950": "#381f2d",
        },
        "th-background": "var(--background)",
        "th-background-secondary": "var(--background-secondary)",
        "th-foreground": "var(--foreground)",
        "th-primary-dark": "var(--primary-dark)",
        "th-primary-medium": "var(--primary-medium)",
        "th-primary-light": "var(--primary-light)",
        "th-accent-dark": "var(--accent-dark)",
        "th-accent-medium": "var(--accent-medium)",
        "th-accent-light": "var(--accent-light)",
        "th-error": "var(--error)",
        "th-disabled": "var(--disabled)",
      },
      backgroundImage: {
        "th-background-gradient": "var(--background-gradient)",
        "th-background-gradient-reversed":
          "var(--background-gradient-reversed)",
      },
    },
  },
  variants: {
    extend: {},
  },
  darkMode: "media",
  plugins: [],
} satisfies Config
